using AI.Domain.Common;

namespace AI.Domain.Feedback;

/// <summary>
/// Stores feedback analysis results generated by AI
/// </summary>
public sealed class FeedbackAnalysisReport : AggregateRoot<Guid>
{

    /// <summary>
    /// When the analysis was performed
    /// </summary>
    public DateTime AnalyzedAt { get; private set; }

    /// <summary>
    /// Number of feedbacks analyzed in this report
    /// </summary>
    public int TotalFeedbacksAnalyzed { get; private set; }

    /// <summary>
    /// Overall summary of the analysis
    /// </summary>
    public string OverallSummary { get; private set; } = string.Empty;

    /// <summary>
    /// JSON serialized categories
    /// </summary>
    public string CategoriesJson { get; private set; } = "[]";

    /// <summary>
    /// JSON serialized improvement suggestions
    /// </summary>
    public string SuggestionsJson { get; private set; } = "[]";

    /// <summary>
    /// Number of high priority suggestions
    /// </summary>
    public int HighPriorityCount { get; private set; }

    /// <summary>
    /// Number of medium priority suggestions
    /// </summary>
    public int MediumPriorityCount { get; private set; }

    /// <summary>
    /// Number of low priority suggestions
    /// </summary>
    public int LowPriorityCount { get; private set; }

    /// <summary>
    /// Start date of the analyzed feedback period
    /// </summary>
    public DateTime? PeriodStart { get; private set; }

    /// <summary>
    /// End date of the analyzed feedback period
    /// </summary>
    public DateTime? PeriodEnd { get; private set; }

    private FeedbackAnalysisReport() { }

    public static FeedbackAnalysisReport Create(
        int totalFeedbacksAnalyzed,
        string overallSummary,
        string categoriesJson,
        string suggestionsJson,
        int highPriorityCount,
        int mediumPriorityCount,
        int lowPriorityCount,
        DateTime? periodStart = null,
        DateTime? periodEnd = null)
    {
        return new FeedbackAnalysisReport
        {
            Id = Guid.NewGuid(),
            AnalyzedAt = DateTime.UtcNow,
            TotalFeedbacksAnalyzed = totalFeedbacksAnalyzed,
            OverallSummary = overallSummary,
            CategoriesJson = categoriesJson,
            SuggestionsJson = suggestionsJson,
            HighPriorityCount = highPriorityCount,
            MediumPriorityCount = mediumPriorityCount,
            LowPriorityCount = lowPriorityCount,
            PeriodStart = periodStart,
            PeriodEnd = periodEnd
        };
    }

    // Navigation property - encapsulated collection
    private readonly List<PromptImprovement> _improvements = new();
    public IReadOnlyCollection<PromptImprovement> Improvements => _improvements.AsReadOnly();

    /// <summary>
    /// Aggregate Root üzerinden yeni improvement oluşturur ve koleksiyona ekler.
    /// DDD invariant koruması: PromptImprovement sadece bu metod ile oluşturulabilir.
    /// </summary>
    public PromptImprovement AddImprovement(
        string category,
        string issue,
        string suggestion,
        string priority,
        string promptModification)
    {
        var improvement = PromptImprovement.Create(Id, category, issue, suggestion, priority, promptModification);
        _improvements.Add(improvement);
        return improvement;
    }
}
